-- ================================================================================
-- 005: CVE_Integrated_Data 테이블 (통합 데이터)
-- ================================================================================

CREATE TABLE IF NOT EXISTS CVE_Integrated_Data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hash_key VARCHAR(64) UNIQUE,
    github_date TEXT,
    github_collect_time TEXT,
    github_link TEXT,
    github_title TEXT,
    github_writer TEXT,
    github_cve TEXT,
    github_readme TEXT,
    github_download_path TEXT,
    github_status TEXT,
    github_trans_msg TEXT,
    github_ai_chk TEXT,
    github_cve_info_status TEXT,
    cve_collect_time TEXT,
    cve_code VARCHAR(50),
    cve_state TEXT,
    cve_date_reserved TEXT,
    cve_date_published TEXT,
    cve_date_updated TEXT,
    cve_product TEXT,
    cve_descriptions TEXT,
    cve_effect_version TEXT,
    cve_cwe_id TEXT,
    cve_attack_type TEXT,
    cve_cvss_score TEXT,
    cve_cvss_vector TEXT,
    cve_cvss_severity TEXT,
    cve_cvss_vector_string TEXT,
    cve_solutions TEXT,
    cve_response_data LONGTEXT,
    ai_cve_summary TEXT,
    ai_step INT,
    ai_packet_text LONGTEXT,
    ai_vuln_stage TEXT,
    ai_stage_description TEXT,
    ai_mitre_tactic TEXT,
    ai_mitre_technique TEXT,
    ai_snort_rule TEXT,
    ai_remediation TEXT,
    ai_expected_response TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_hash_key (hash_key),
    INDEX idx_cve_code (cve_code),
    INDEX idx_github_link (github_link(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
